[package]
name = "rust-test-2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
amqprs = "1.4.0"
tokio = "1"
tracing-subscriber = {version = "0.3", features = ["env-filter"]}